### ISSUE TITLE
Gibbs free energy at different temperatures

### ISSUE THREAD

**Issue by chemistza** [grimme-lab/CENSO#13]
Hi
Is there a way of re-doing the thermostatistical calculations and Boltzmann averaging for a different range of temperatures on a completed CENSO run?

Thanks

**Comment by fabothch** [comment]
This is currently not really implemented. But I also found myself in the need for this feature and will make this available in the next version.

**Comment by chemistza** [comment]
Fantastic, thanks.

Chris

Dr Christopher B. Perry
Senior Research Scientist

***@***.***D74CCA.7FADCB80]<http://www.matthey.com/>

Johnson Matthey
Building 22, CSIR, Meiring Naudé Road
Brummeria, Pretoria, South Africa
T +27 (0)12 842 7840
***@***.******@***.***>

www.matthey.com<http://www.matthey.com/>
Follow us on: Twitter<https://twitter.com/Johnson_Matthey> | LinkedIn<https://www.linkedin.com/organization/7655> | Instagram<https://www.instagram.com/johnson_matthey/>

**Comment by fabothch** [comment]
Dear chemistza,

the option to reevaluate the Boltzmann factors of your final ensemble is implemented with #14. The restart is only possible if all temperature dependent contributions to free energy have been calculated in the previous run! Additionally a word of caution: the sorting of the final ensemble depends upon thresholds and for larger temperatures larger thresholds should be applied. Otherwise a falsely to small ensemble is reevaluated.  Also for systems in solution (from the implicit solvation models available here) only COSMO-RS has a temperature dependence. To evaluate your ensemble at a different temperature run `censo -restart --temperature **the_new_temperature**`
But this feature is only available starting from version 1.1.0 which is not compatible to older versions!

Best,

Fabian
