### ISSUE TITLE
Changing Orca SCF settings for Part1 amd Part2 computations

### ISSUE THREAD

**Issue by ankur56** [grimme-lab/CENSO#31]
Hello,

I am using CENSO to screen metal complexes with different spin multiplicities. In many cases, the SCF convergence is painfully slow, potentially because of the default Orca setting of using the TRAH method quite early during the SCF procedure. Therefore, I would like to add some keywords in the CENSO-generated Orca input files to make the SCF convergence faster. However, I couldn't find any keyword in .censorc that would be useful for my needs. Is there any way I could modify Part-1 and Part-2 generated input files through CENSO?

**Comment by fabothch** [comment]
Hi,

since CENSO v.1.2.0  a modification of input files  for **all** ORCA calculation is possible:

- A new file `censo_ORCA_editable.dat` is introduced to the directory `~/.censo_assets/` and will be created upon the next start of CENSO. It contains ORCA keywords which will be added to **every** ORCA-input generated by CENSO, therefore it can only contain global information independent of specific calculation types.  There exists no check for misspelling so typos will lead to crashes. The intention is to enable the user to specify additional input like for example "NOTRAH". This feature is considered to be an **expert-user-option**. The file looks like this:
 ```
! smallprint printgap noloewdin
! NOSOSCF
%MaxCore 8000
%output
       print[P_BondOrder_M] 1
       print[P_Mayer] 1
       print[P_basis] 2
end
```
You can add the  NOTRAH keyword if this is better suiting your use case. 

All the best,

Fabian

**Comment by ankur56** [comment]
Hi Fabian,

This is precisely what I wanted.  Thank you for your help. There is another small related issue I was wondering if it could be resolved.

I would like to save forces for all the Part-1 geometries. I know that I could add the `engrad` keyword to the `censo_ORCA_editable.dat` file to generate forces for Part-1 structures. However, that would conflict with the `engrad` keyword added by CENSO in Part 2. Therefore, I was wondering if we could have separate Orca input files for Part-1 and Part-2.
